### ISSUE TITLE
Create integration interface in device tab

### ISSUE THREAD

**Issue by mvroosmalen1970** [aceindy/Duepi_EVO#19]
Feature request. 

Can we create an integration interface so users can enter the settings there and when changes have been made to the code we can reload the new code.

Mark

**Comment by aceindy** [comment]
That would mean I have to get this repository added to HA core (instead of HACS), which is a bit too much work for me...
Besides, I am about to abandon the project, as I will be moving to a new house; since this house will be energy-neutral I cannot keep my pellet stove (which I regret, as I like my stove )
