### ISSUE TITLE
Compatibility with original Wi-Fi card

### ISSUE THREAD

**Issue by Nilan464** [aceindy/Duepi_EVO#48]
Is this compatible with an official Wi-Fi card?
I have a stove that I can control with the MyDPremote app that I would like to connect to Home Assistant.

**Comment by aceindy** [comment]
@Nilan464 , No it won't (mainly due to the welcome messages send by the module during startup:
https://community.home-assistant.io/t/pellet-stove-duepi-evo/255841/27?u=aceindy

However, the reverse will work; you can still use your MtDPRemote (locally) with the ESP module.
However, not all models report the setpoint back (so it won't be updated in HA), but otherwise it works fine ;)
